# Generated by Django 5.1.2 on 2024-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0002_category_registration_subcategory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categoryimage',
            field=models.FileField(default=None, upload_to='img/'),
        ),
    ]
