# Generated by Django 5.1.2 on 2024-12-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='roductprice',
            new_name='productprice',
        ),
    ]
