# Generated by Django 5.1.2 on 2024-12-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0007_rename_roductprice_cart_productprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartdata',
        ),
    ]
