# Generated by Django 5.1.2 on 2024-12-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0009_alter_userregistration_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
