# Generated by Django 5.1.2 on 2024-12-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0013_alter_cartdata_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdata',
            name='quantity',
        ),
    ]
