# Generated by Django 5.1.2 on 2024-12-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0014_remove_cartdata_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdata',
        ),
    ]
