# Generated by Django 5.1.2 on 2024-12-13 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0016_cartdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdata',
            name='productprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.product_unit'),
        ),
    ]
