# Generated by Django 5.1.2 on 2024-12-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0017_alter_cartdata_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdata',
            name='productprice',
            field=models.IntegerField(),
        ),
    ]
